// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ConvertElementToIcon(arg1:main.Element):Promise<string>;

export function G_ChooseColour(arg1:number):Promise<Array<number>>;

export function GetCharacters():Promise<Array<main.Character>>;

export function Greet(arg1:string):Promise<string>;
