// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConvertElementToIcon(arg1) {
  return window['go']['main']['App']['ConvertElementToIcon'](arg1);
}

export function G_ChooseColour(arg1) {
  return window['go']['main']['App']['G_ChooseColour'](arg1);
}

export function GetCharacters() {
  return window['go']['main']['App']['GetCharacters']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}
