// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddCharacter(arg1:main.Character):Promise<void>;

export function GetCharacters():Promise<Record<string, main.Character>>;
