// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddCharacter(arg1) {
  return window['go']['main']['App']['AddCharacter'](arg1);
}

export function GetCharacters() {
  return window['go']['main']['App']['GetCharacters']();
}

export function UpdateCharacter(arg1, arg2) {
  return window['go']['main']['App']['UpdateCharacter'](arg1, arg2);
}
